<a href="https://colab.research.google.com/github/adarshnitt/csoe34/blob/main/colab_practice_1_ipynbactice_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# firstly came pivot then lower then upper
# lower and upper both are greater than pivot
# new data will be from  data[0, lower] and data[lower, upper]

def quick(d,l,r):
  if r-l<=1:
    return d
  p=d[l]
  lower=l+1
  upper=l+1
  for i in range(l+1,r):
    if d[i]>p:
      upper=upper+1
    else:
      d[i],d[lower]=d[lower],d[i]
      lower,upper=lower+1,upper+1
  d[l],d[lower-1]=d[lower-1],d[l]
  lower=lower-1
  quick(d,l,lower)
  quick(d,lower+1,upper)
  return d
d=[1,2,3,4,5,55,90]
quick(d,0,7)
      

[1, 2, 3, 4, 5, 55, 90]

In [ ]:
# djkistra algo
elem=[0,1,2,3,4,5,6]
relation={0:[(1,10),(2,80)],1:[(0,10),(2,6),(4,20)],
          2:[(3,70),(1,6),(0,80)],3:[(2,70)],4:[(1,20),
                                                (5,50),(6,5)],5:[(4,50),(6,10)],6:[(4,5),(5,10)]}

In [ ]:
for new, leng in relation[0]:
  print(new,leng)

1 10
2 80


In [ ]:
def start(relation,elem):
  status={}
  for i in elem:
    status[i]=False
  return status
start(relation,elem)

{0: False, 1: False, 2: False, 3: False, 4: False, 5: False, 6: False}

In [ ]:
status=start(relation,elem)
time=0
go={}
final=[]
def djkrista(relation,node, time):
  
  global go
  global final 
  #global time
  global status
  final.append(node)
  status[node]=True
 # print("hii",final)


  for new, leng in relation[node]:
    try:
      old=go[new]
      if old > (time+leng):
        if status[new] is False:
          go[new]=time+leng
    except:
      if status[new] is False:
        go[new]=time+leng 

  min=100000
  for i in list(go.keys()):
     if status[i] is False:
       if go[i]<min:
         min=go[i]
         node=i
  time=min
  if status[node] is False:
    djkrista(relation,node,time)
  return
djkrista(relation,0,0)
final


hii [0]
hii [0, 1]
hii [0, 1, 2]
hii [0, 1, 2, 4]
hii [0, 1, 2, 4, 6]
hii [0, 1, 2, 4, 6, 5]
hii [0, 1, 2, 4, 6, 5, 3]


[0, 1, 2, 4, 6, 5, 3]

In [ ]:
# djkastra algo
# djkistra algo
elem=[0,1,2,3,4,5,6]
relation={0:[(1,10),(2,80)],1:[(0,10),(2,6),(4,20)],
          2:[(3,70),(1,6),(0,80)],3:[(2,70)],4:[(1,20),
                                                (5,50),(6,5)],5:[(4,50),(6,10)],6:[(4,5),(5,10)]}



def start(relation,elem):
  status={}
  for i in elem:
    status[i]=False
  return status
start(relation,elem)


status=start(relation,elem)
time=0
go={}
final=[]
def djkrista(relation,node, time):
  
  global go
  global final 
  #global time
  global status
  final.append(node)
  status[node]=True
 # print("hii",final)


  for new, leng in relation[node]:
    try:
      old=go[new]
      if old < (time+leng):
        if status[new] is False:
          go[new]=time+leng
    except:
      if status[new] is False:
        go[new]=time+leng 

  min=100000
  for i in list(go.keys()):
     if status[i] is False:
       if go[i]<min:
         min=go[i]
         node=i
  time=min
  if status[node] is False:
    djkrista(relation,node,time)
  return
djkrista(relation,0,0)
final


In [ ]:
# prrims
# sort
def quick(data,s,f):
  if (f-s)<=1:
   # print(data[s:f],"ooo")
    return 
  p=data[s]
 # print(p,s,f)
  l=s+1
  for i in range(s+1,f,1):
    if data[i]<p:
      data[i],data[l]=data[l],data[i]
      l+=1
  data[l-1],data[s]=data[s],data[l-1]
  l=l-1
  u=f
  quick(data,s,l+1)
  quick(data,l+1,u)
  return data

a=[11,2,33,4,5,6,111,90]
quick(a,0,len(a))

[2, 4, 5, 6, 11, 33, 90, 111]

In [ ]:
visited={}
def quick(data,i,j):
    if j-i<=1:
        return 
    pivot=data[i][-1]
    visited[data[i][0]]=False
    visited[data[i][1]]=False
    lower=i+1
    upper=j
    for k in range(i+1,j):
        if data[k][-1]<pivot:
          data[k],data[lower]=data[lower],data[k]
          lower+=1 

    #print(data)
    data[i],data[lower-1]=data[lower-1],data[i]
    lower=lower-1
    quick(data,i,lower+1)
    quick(data,lower+1,upper)
    return data


data=[(0,1,10),(0,2,50),(0,3,300),(5,6,45),(2,1,30),(6,4,37),(1,6,65),(2,5,76),
(1,3,40),(3,4,60),(2,4,20)]
quick(data,0,len(data))

[(0, 1, 10),
 (2, 4, 20),
 (2, 1, 30),
 (6, 4, 37),
 (1, 3, 40),
 (5, 6, 45),
 (0, 2, 50),
 (3, 4, 60),
 (1, 6, 65),
 (2, 5, 76),
 (0, 3, 300)]

In [ ]:
new={}
for i in data:
  try:
    new[i[0]].append((i[1],i[2]))
  except:
    new[i[0]]=[]
    new[i[0]].append((i[2],i[1]))
new
def path(data,s):
  global new
  old=[]
  old.append(s)
  while old:
    m=min(new[old[-1]])
    



{0: [(1, 10), (2, 50), (3, 300)],
 1: [(3, 40), (6, 65)],
 2: [(4, 20), (1, 30), (5, 76)],
 3: [(4, 60)],
 5: [(6, 45)],
 6: [(4, 37)]}

In [ ]:
for i in data:
  print(visited[i[0]]==False)

True
True
True
True
True
True
True
True
True
True
True


In [ ]:
def quick(data,i,j):
  if j-i<=1:
    return
  lower=i+1
  upper=j
  pivot=data[i]
  for k in range(i+1,j):
    if data[k]<pivot:
      data[k],data[lower]=data[lower],data[k]
      lower=lower+1
  data[i],data[lower-1]=data[lower-1],pivot
  lower=lower-1
  #print(data)
  quick(data,i,lower+1)
  quick(data,lower+1,upper)
  return data
data=[1111,22,27,44]
quick(data,0,len(data))

[22, 27, 44, 1111]

In [ ]:
a=[1,2,3]
a[0:4]

[1, 2, 3]

In [ ]:
# topological sorting
# how work will be done, which work is ;[more prior to other one
data={0:[2,3],1:[2,3,4],2:[7],3:[5,6],4:[6],5:[7],6:[7],7:[]}

In [ ]:
# code for toplogical sorting
def prior(data):
  indegree={}
  zerodegree=[]
  toposort=[]
  for i in list(data.keys()):
    indegree[i]=0
  for j in list(data.keys()):
    for k in data[j]:
      indegree[k]=indegree[k]+1
  for i in list(indegree.keys()):
    if indegree[i]==0:
      zerodegree.append(i)
  return indegree,zerodegree,toposort

In [ ]:
indegree,zerodegree,toposort=prior(data)
def topa(data):
  global indegree
  global zerodegree
  global toposort
  for i in zerodegree:
    toposort.append(i)
    indegree[i]=-1
    zerodegree.remove(i)
    for j in data[i]:
      indegree[j]-=1
  for i in list(indegree.keys()):
    if indegree[i]==0:
      zerodegree.append(i)
  while len(zerodegree)!=0:
    topa(data)
  return

In [ ]:
topa(data)
indegree,zerodegree,toposort

({0: -1, 1: -1, 2: -1, 3: -1, 4: -1, 5: -1, 6: -1, 7: -1},
 [],
 [0, 1, 1, 3, 2, 5, 4, 6, 7])

In [ ]:
# no of linked cycles in dgraph:
data={0:1,1:2,2:3,3:4,4: None,5:None,6:7,7:8,8:9,9:None}

In [ ]:
def track(data):
  visited={}
  for i in list(data.keys()):
    visited[i]=False
  return visited

In [ ]:
visited=track(data)
count=0
cycle={}
def comp(data):
  global visited
  global count
  global cycle
  for i in list(data.keys()):
    if visited[i] is False:
      visited[i]=True
      try: 
        cycle[count].append(i)
      except:
        cycle[count]=[]
        cycle[count].append(i)
    if data[i] is None:
      #print(data[i])
      count+=1
  return 


In [ ]:
comp(data)
cycle

{0: [0, 1, 2, 3, 4], 1: [5], 2: [6, 7, 8, 9]}

In [ ]:
# bFS
def bfs(data,node):
  visited={}
  parent={}
  out=[node]
  for i in list(data.keys()):
    visited[i]=False
    parent[i]=-1
  found=[node]
  visited[node]=True
  parent[node]=None
  while found:
    f=found.pop(0)
    for j in data[f]:
      if visited[j]==False:
        found.append(j)
        out.append(j)
        parent[j]=f
        visited[j]=True
  return visited,parent,out
bfs(data,0)

({0: True, 1: True, 2: True, 3: True, 4: True, 5: True, 6: True, 7: True},
 {0: None, 1: 0, 2: 0, 3: 2, 4: 2, 5: 2, 6: 4, 7: 0},
 [0, 1, 2, 7, 3, 4, 5, 6])

In [ ]:
data={0:[1,2,7],1:[2],2:[3,4,5],3:[7],4:[5,6],5:[6],6:[7],7:[]}

In [ ]:
def quick(data,l,r):
  if len(data[l:r])<=1:
    return d
  p=data[l]
  lw=l+1
  up=l+1
  for i in range(l+1,r):
    if data[i]>p:
      up+=1
    else:
      data[i],data[lw]=data[lw],data[i]
      lw+=1
      up+=1
  data[l],data[lw-1]=data[lw-1],data[l]
  lw=lw-1
  quick(data,l,lw)
  quick(data,lw+1,up)
  return data
d=[1 ,2, 3, 4, 4, 5, 6, 6 ,6 ,7 ,6, 6, 6, 5, 4, 4, 3, 2, 1]
quick(d,0,5)

[2, 4, 5, 8, 10]

In [ ]:
# dfs
def init(data):
  visited,parent={},{}
  for i in list(data.keys()):
    l=len(data[i])
    for j in range(l):
      parent[data[i][j]]=[]
      visited[i]=False
  return visited,parent
init(data)

({0: False, 1: False, 2: False}, {1: [], 2: [], 3: []})

In [ ]:
visited,parent=init(data)
def dfs(list,n):
  global visited
  global parent
  visited[n]=True
  try:
    l=len(list[n])
    for i in range(l):
      parent[list[n][i]].append(n)
      #print(list[n][i])
      dfs(list,list[n][i])
  except:
    pass
  return
dfs(list,0)
list?

In [ ]:
data={0:[1],
      1:[2],
      2:[3]}
list(data.keys())

[0, 1, 2]

In [ ]:
visited,parent

({0: True, 1: True, 2: True, 3: True}, {0: None, 1: 0, 2: 1, 3: 2})

In [ ]:
data={0:[1],
      1:[2],
      2:[3]}

visited,parent=init(data)
dfs(data,0)
visited,parent

({0: True, 1: True, 2: True, 3: True}, {1: [0], 2: [1], 3: [2]})

In [ ]:
vert="1 2 3 4 5 6 7 8".split(" ")
vertices={}
edge={}
for i in vert:
    vertices[i]=False
    edge[i]=[]
n=6

for i in range(n):
    d=input().split(" ")
    edge[d[0]].append(d[1])
count=1

def loop(data):
    contain=[]
    for i in list(data.keys()):
        if visited[i] is False:
            contain.append(i)
            break
    while contain:
        elem=contain.pop(0)
        visited[elem]=True
        try: 
            for j in data[j]:
                contain.append(j)
        except:
            continue
    count+=1
    loop(data)
    return 

print(count)

1 3
2 3
1 4
2 4
3 4
5 6
0


In [ ]:
# longest path
data={0:[2,4,3],1:[2,7],2:[5],4:[7],3:[5,7],5:[6],6:[7]}

In [ ]:
def pre(data):
  indegree=dict(zip([i for i in list(data.keys()) ],[0]*len( list(data.keys()))))
  for i in list(data.keys()):
    for j in data[i]:
      indegree[j]=indegree[i]+1
  return indegree
pre(data)

{0: 0, 1: 0, 2: 1, 3: 1, 4: 1, 5: 2, 6: 3, 7: 4}

In [ ]:
def prep(data):
  visited={}
  outdegree={}
  for i in list(data.keys()):
    visited[i]=False
    try:
      outdegree[i]=len(data[i])
    except:
      outdegree[i]=0
  return outdegree, visited
data={1:[2,4],2:[3],3:[5],5:[6,8],4:[3,7],7:[8],6:None,8:None}
prep(data)

({1: 2, 2: 1, 3: 1, 4: 2, 5: 2, 6: 0, 7: 1, 8: 0},
 {1: False,
  2: False,
  3: False,
  4: False,
  5: False,
  6: False,
  7: False,
  8: False})

In [ ]:
final=[]
outdegree, visited=prep(data)
def dfs( data, node):
  global final
  global outdegree
  global visited
  if outdegree[node]!=0 and visited[node]==False:
    final.append(node)
    for i in data[node]:
      outdegree[node]-=1
      if outdegree[node]==0:
        visited[node]=True
      dfs(data,i)
  if outdegree[node]==0 and visited[node]==False:
    final.append(node)
  visited[node]=True
  return
dfs(data,1)
final


[1, 2, 3, 5, 6, 8, 4, 7]

In [ ]:
import numpy as np
from numpy  import where

In [ ]:
a=[True,True,True]
b=[False,False,True,False,True]
c=[1,2,3,4]

where(b)

(array([2, 4]),)

In [ ]:
where(a*b)

TypeError: ignored

In [ ]:
import numpy as np
x=np.arange(0,100,2)
print(x,len(x))

[ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46
 48 50 52 54 56 58 60 62 64 66 68 70 72 74 76 78 80 82 84 86 88 90 92 94
 96 98] 50


In [ ]:
np.zeros(shape=[2,2])

array([[0., 0.],
       [0., 0.]])

In [ ]:
s=np.where(xx)
s

(array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36,
        37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49]),)

In [ ]:
z=y*yy
z

array([False,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True])

In [ ]:
yy

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True])

In [ ]:
np.where(yy)

(array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
        17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
        34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49]),)

In [ ]:
!find / -iname 'libdevice'
!find / -iname 'libnvvm.so'


/usr/local/lib/python3.7/dist-packages/jaxlib/cuda/nvvm/libdevice
/usr/local/cuda-10.1/nvvm/libdevice
/usr/local/cuda-11.0/nvvm/libdevice
/usr/local/cuda-10.0/nvvm/libdevice
/usr/local/cuda-10.1/nvvm/lib64/libnvvm.so
/usr/local/cuda-11.0/nvvm/lib64/libnvvm.so
/usr/local/cuda-10.0/nvvm/lib64/libnvvm.so


In [ ]:
import os
os.environ['NUMBAPRO_LIBDEVICE'] = "/usr/local/cuda-10.0/nvvm/libdevice"
os.environ['NUMBAPRO_NVVM'] = "/usr/local/cuda-10.0/nvvm/lib64/libnvvm.so"

In [ ]:
import pandas as pd
import random

In [ ]:
a=([1,2,3],[22,33,44],[331,441,551])
b=np.square(a)

In [ ]:
from numba import vectorize
import math

In [ ]:
@vectorize([(int64[:],int64[:])],"(n)->(n)")
def s(x,y):
  y=np.square(x)


NameError: ignored

In [120]:
# 26 october 2021
# binary tree

class binary:
  def __init__(self,v1=None):
    self.value=v1
    if self.value:
      self.left=binary()
      self.right=binary()
    else:
      self.left=None
      self.right=None
    return 
  def isleaf(self):
    if self.left==None and self.right==None and (self.value !=None):
      return True
    else:
      return False
  def find(self,v):
    if self==v and self:
      return True
    if v< self.value:
      return sef.left.find(v)
    else:
      return sef.right.find(v)
  def min(self):
    if self.isnull():
      return []
    if self.left.isnull():
      return self.value
    else:
      return self.left.min()
  def max(self):
    if self.isnull():
      return []
    if self.right.isnull():
      return self.value
    else:
      return self.right.max()
  def insert(self,v):
    if self.isnull():
      self.value=v
      self.left=binary()
      self.right=binary()
    elif v< self.value:
      if v< self.value:
        self.left.insert(v)
    else:
      if v>self.value:
        self.right.insert(v)
  def isnull(self):
    return (self.value==None)
  def inorder(self):
    if self.isnull():
      return []
    else:
      self.left.inorder()
      self.right.inorder()
      return (self.left.inorder()+[self.value]+self.right.inorder())
  # disaply string 
  def delete(self,v):
    if self.isnull():
      return
    if v>self.value:
      self.right.delete(v)
    if v< self.value:
      self.left.delete(v)
    if self.value==v:
      if self.left.isnull() and self.right.isnull():
        self.value=None
        return
      elif self.left.value==v:
      . 




 
a=binary(7)
a.insert(2)
a.insert(9)
a.insert(0)

a.insert(999)
a.insert(-9)
a.inorder()

[-9, 0, 2, 7, 9, 999]

In [41]:
if []:
  print("j")
else:
  print("kkk")

kkk


In [43]:
__str__?

Object `__str__` not found.
