<a href="https://colab.research.google.com/github/adarshnitt/csoe34/blob/main/colab_practice_1_ipynbactice_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [18]:
# firstly came pivot then lower then upper
# lower and upper both are greater than pivot
# new data will be from  data[0, lower] and data[lower, upper]

def quick(d,l,r):
  if r-l<=1:
    return d
  p=d[l]
  lower=l+1
  upper=l+1
  for i in range(l+1,r):
    if d[i]>p:
      upper=upper+1
    else:
      d[i],d[lower]=d[lower],d[i]
      lower,upper=lower+1,upper+1
  d[l],d[lower-1]=d[lower-1],d[l]
  lower=lower-1
  quick(d,l,lower)
  quick(d,lower+1,upper)
  return d
d=[99,7,6,9999,0,3,78]
quick(d,0,7)
      

[0, 3, 6, 7, 78, 99, 9999]

In [100]:
def quick(data,l,r):
  if len(data[l:r])<=1:
    return d
  p=data[l]
  lw=l+1
  up=l+1
  for i in range(l+1,r):
    if data[i]>p:
      up+=1
    else:
      data[i],data[lw]=data[lw],data[i]
      lw+=1
      up+=1
  data[l],data[lw-1]=data[lw-1],data[l]
  lw=lw-1
  quick(data,l,lw)
  quick(data,lw+1,up)
  return data
d=[1 ,2, 3, 4, 4, 5, 6, 6 ,6 ,7 ,6, 6, 6, 5, 4, 4, 3, 2, 1]
quick(d,0,5)

[2, 4, 5, 8, 10]

In [76]:
import numpy as np
from numpy  import where

In [84]:
a=[True,True,True]
b=[False,False,True,False,True]
c=[1,2,3,4]

where(b)

(array([2, 4]),)

In [85]:
where(a*b)

TypeError: ignored

In [89]:
import numpy as np
x=np.arange(0,100,2)
print(x,len(x))

[ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46
 48 50 52 54 56 58 60 62 64 66 68 70 72 74 76 78 80 82 84 86 88 90 92 94
 96 98] 50


In [91]:
np.zeros(shape=[2,2])

array([[0., 0.],
       [0., 0.]])

In [74]:
s=np.where(xx)
s

(array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36,
        37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49]),)

In [52]:
z=y*yy
z

array([False,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True])

In [58]:
yy

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True])

In [57]:
np.where(yy)

(array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
        17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
        34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49]),)

In [ ]:
!find / -iname 'libdevice'
!find / -iname 'libnvvm.so'


/usr/local/lib/python3.7/dist-packages/jaxlib/cuda/nvvm/libdevice
/usr/local/cuda-10.1/nvvm/libdevice
/usr/local/cuda-11.0/nvvm/libdevice
/usr/local/cuda-10.0/nvvm/libdevice
/usr/local/cuda-10.1/nvvm/lib64/libnvvm.so
/usr/local/cuda-11.0/nvvm/lib64/libnvvm.so
/usr/local/cuda-10.0/nvvm/lib64/libnvvm.so


In [ ]:
import os
os.environ['NUMBAPRO_LIBDEVICE'] = "/usr/local/cuda-10.0/nvvm/libdevice"
os.environ['NUMBAPRO_NVVM'] = "/usr/local/cuda-10.0/nvvm/lib64/libnvvm.so"

In [ ]:
import pandas as pd
import random

In [ ]:
a=([1,2,3],[22,33,44],[331,441,551])
b=np.square(a)

In [ ]:
from numba import vectorize
import math

In [ ]:
@vectorize([(int64[:],int64[:])],"(n)->(n)")
def s(x,y):
  y=np.square(x)


NameError: ignored